create database CarsIndia;

drop database carsindia;

select * from hyundai_company;
select * from maruti_suzuki_company;
select * from tata_company;
select * from mahindra_company;
select * from toyota_company;
select * from kia_company;
select * from honda_company;
select * from mg_company;
select * from renault_company;
select * from volkswagen_company;
select * from skoda_company;
select * from nissan_company;
select * from citroen_company;
select * from jeep_company;
select * from force_company;
select * from isuzu_company;  

/* common table expression query */ 
select * from carcompanies;


/* A. Performance Comparison Across Brands */ 
/* 1. Which car company sold the most units in FY24? */
select company_name, sum(no_of_units_sold_in_FY24) as total_units_sold
from CarCompanies
group by company_name
order by total_units_sold desc
limit 1;

/* 2. What is the total profit made by each company in FY24? */
select company_name, sum(profit_by_model) as total_profit
from CarCompanies
group by company_name
order by total_profit desc;

/* 3. Which car company has the highest average ex-showroom price in FY24? */
select company_name, avg(ex_showroom_price_from) as avg_ex_showroom_price
from CarCompanies
group by company_name
order by avg_ex_showroom_price desc
limit 1;

/* 4. Which car company has the highest number of car variants available in FY24? */
select company_name, max(length(variants) - length(replace(variants, ',', '')) + 1) as total_variants
from CarCompanies
group by company_name
order by total_variants desc
limit 1;

/* 5. What is the total revenue generated by each company in FY24? */
select company_name, sum(estimated_revenue) as total_revenue
from CarCompanies
group by company_name
order by total_revenue desc;
 
/* 6. What is the average fuel mileage of each company in FY24? */
select company_name,
    avg(case when fuel_type = 'Petrol' then mileage end) as avg_petrol_mileage,
    avg(case when fuel_type = 'Diesel' then mileage end) as avg_diesel_mileage,
    avg(case when fuel_type = 'Electric' then mileage end) as avg_electric_range
from CarCompanies
group by company_name
order by company_name;

/* 7. Which car company has the highest tank capacity in FY24? */
select company_name, max(tank_capacity) as max_tank_capacity
from CarCompanies
where tank_capacity <> 'na'
group by company_name
order by max_tank_capacity desc
limit 1;

/* 8. Which car company has the highest number of units sold per month on average in FY24? */
select company_name, sum(no_of_units_sold_in_FY24) / 12 as total_units_sold_per_month
from CarCompanies
group by company_name
order by total_units_sold_per_month desc
limit 1;

/* 9. Which car company has the most number of cars with NCAP safety ratings in FY24? */
select company_name, count(distinct car_id) as cars_with_ncap_rating
from CarCompanies
where ncap_test <> '0'
group by company_name
order by cars_with_ncap_rating desc;

/* 10. What is the total boot space (in liters) for each car company’s fleet in FY24? */
select company_name, sum(boot_space) as total_boot_space
from CarCompanies
group by company_name
order by total_boot_space desc;


/* B. Fuel Efficiency and Pricing Analysis */
/* 1. Which car models have the highest fuel efficiency? */
select model_name, mileage
from carcompanies
where fuel_type <> 'electric'
order by mileage desc
limit 10;

/* 2. What is the average fuel efficiency for each brand? */
select company_name, origin, avg(mileage) as avg_mileage
from carcompanies
where fuel_type <> 'electric'
group by company_name, origin
order by company_name asc;

/* 3. Which brand has the most number of CNG cars in the dataset and what are their average prices? */
select company_name, count(*) as cng_count, avg(on_road_price_from) as avg_price
from carcompanies
where fuel_type <>'Petrol, diesel'
group by company_name
order by cng_count desc
limit 1;

/* 4. What is the correlation between fuel efficiency and on_road_price_from? */
select model_name, mileage, on_road_price_from
from carcompanies
where mileage is not null and on_road_price_from is not null
and fuel_type <> 'electric';

/* 5. Which cars have the best fuel efficiency (top 5 models) with a price below ₹10 Lakhs? */
select model_name, mileage, on_road_price_from
from carcompanies
where on_road_price_from between '10L' and '15L'
and mileage between '18.0' and '26.0'
and fuel_type <> 'electric'
order by mileage desc;

/* 6. What is the average fuel efficiency for cars in each engine capacity range? */ 
select 
    case
        when engine_capacity < 1000 then 'Below 1000cc'
        when engine_capacity between 1000 and 1500 then '1000cc - 1500cc'
        when engine_capacity between 1500 and 2000 then '1500cc - 2000cc'
        else 'Above 2000cc'
    end as engine_capacity_range,
    avg(mileage) as avg_mileage
from carcompanies
where fuel_type <> 'electric'
group by engine_capacity_range;

/* 7. What is the difference in fuel efficiency between diesel and petrol cars? */
select fuel_type, avg(mileage) as avg_mileage
from carcompanies
where fuel_type in ('Petrol', 'Diesel')
group by fuel_type;

/* 8. Which models have the best mileage and come with a 7-seater configuration? */
select model_name, mileage, seater_count
from carcompanies
where seater_count = 7
order by mileage desc
limit 5;

/* 9. How does the on-road price correlate with the fuel type? */
select fuel_type, avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by fuel_type;

/* 10. What is the distribution of car models by engine displacement and engine type? */
select engine_displacement, engine_name, COUNT(*) as model_count
from carcompanies
where fuel_type <> 'electric'
group by engine_displacement, engine_name
order by engine_displacement, engine_name;


/* C. Market Trends and Consumer Preferences */
/* 1. What is the total number of units sold across all car companies in FY24? */
select sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies;

/* 2. Which car model has the highest number of units sold in FY24? */
select model_name, max(no_of_units_sold_in_FY24) as max_units_sold
from carcompanies
group by model_name
order by max_units_sold desc
limit 1;

/* 3. How have sales evolved by month (grouped by first_sale_date) through companies? */
select company_name,
	   extract(month from first_sale_date) as month, 
       sum(no_of_units_sold_in_FY24) as units_sold
from carcompanies
group by company_name, month 
order by company_name, month;

/* 4. What is the relationship between car seating capacity and units sold in FY24? */
select seater_count, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by seater_count
order by total_units_sold desc;

/* 5. Which fuel type has the highest number of units sold in FY24? */
select fuel_type, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by fuel_type
order by total_units_sold desc
limit 1;

/* 6. Which car model has the highest average on-road price? */
select model_name, avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by model_name
order by avg_on_road_price desc
limit 1;

/* 7. How do sales numbers vary based on engine displacement? */
select engine_displacement, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
where fuel_type <> 'electric'
group by engine_displacement
order by total_units_sold desc;

/* 8. How does the profitability of car models relate to their engine capacity? */
select engine_capacity, sum(profit_by_model) as total_profit
from carcompanies
group by engine_capacity
order by total_profit desc;

/* 9. What is the average boot space across different car types (SUV, Sedan, etc.)? */
select model_type, avg(boot_space) as avg_boot_space
from carcompanies
group by model_type
order by avg_boot_space desc;

/* 10. What is the average number of models sold per month by car company? */
select company_name, avg(avg_models_per_month) as avg_sales_per_month
from carcompanies
group by company_name
order by avg_sales_per_month desc;


/* D. Impact of Car Specifications on Sales Performance */
/* 1. How do different engine displacements (engine_capacity) correlate with sales performance (no_of_units_sold_in_FY24)? */
select engine_capacity, 
       avg(no_of_units_sold_in_FY24) as avg_units_sold
from carcompanies
group by engine_capacity
order by engine_capacity;

/* 2. What is the sales performance based on transmission type? */
select transmission_name, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by transmission_name
order by total_units_sold desc;

/* 3. Is there a significant difference in sales performance between different fuel types? */
select fuel_type, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by fuel_type
order by total_units_sold desc;

/* 4. How do variants (like base, mid, top) affect the number of units sold? */
select variants, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by variants
order by total_units_sold desc;

/* 5. How do car sales vary based on the manufacturing locations in India? */
select manufacturing_locations_in_india, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by manufacturing_locations_in_india
order by total_units_sold desc;

/* 6. What is the average price difference between different engine types (e.g., petrol vs diesel) in relation to sales performance? */
select engine_name, 
       avg(ex_showroom_price_from) as avg_price, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by engine_name
order by total_units_sold desc;

/* 7. Do cars with larger boot space sell more than those with smaller boot space? */
select boot_space, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by boot_space
order by total_units_sold desc;

/* 8. What is the impact of NCAP safety ratings on sales? */
select ncap_test, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by ncap_test
order by total_units_sold desc;

/* 9. How does the first sale date correlate with the number of units sold in FY24? */
select first_sale_date, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by first_sale_date
order by first_sale_date;

/* 10. What is the correlation between tank capacity and fuel efficiency (mileage)? */
select tank_capacity, 
       avg(mileage) as avg_mileage
from carcompanies
group by tank_capacity
order by tank_capacity;


/* E. Overall Market Trends and Industry Growth in FY24 */
/* 1. What is the total number of units sold by all car companies in FY24? */
select sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies;

/* 2. What is the total estimated revenue generated across all car brands in FY24? */
select sum(estimated_revenue) as total_revenue
from carcompanies;

/* 3. Which company origin had the highest total sales in FY24? */
select origin, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by origin
order by total_sales desc
limit 1;

/* 4. What is the average price of cars sold across all brands in FY24? */
select avg(on_road_price_from) as average_price
from carcompanies;

/* 5. What is the total number of variants offered across all brands in FY24? */
select model_name,
       variants,
       length(variants) - length(replace(variants, ' ', '')) + 1 as word_count
from carcompanies
where variants is not null
order by model_name;

/* 6. Which engine displacement has the highest number of units sold in FY24? */
select engine_displacement, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by engine_displacement
order by total_sales desc
limit 1;

/* 7. What is the total profit across all brands for FY24? */
select sum(profit_by_model) as total_profit
from carcompanies;

/* 8. What is the average profit and loss across all models for each company in FY24? */
select company_name, 
       avg(profit_by_model) as average_profit,
       avg(loss_by_model) as average_loss
from carcompanies
group by company_name;

/* 9. What is the total boot space offered across all car brands in FY24? */
select sum(boot_space) as total_boot_space
from carcompanies;

/* 10.  What are the top 5 models with the highest units sold across all brands in FY24? */
select model_name, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by model_name
order by total_sales desc
limit 5;


/* F. Sales and Profitability by Model Type (SUV vs Sedan vs Others) */
/* 1. What is the total number of units sold for each model type (SUV, Sedan, Other)? */
select model_type, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by model_type;

/* 2. What is the total profit for each model type (SUV, Sedan, Other)? */
select model_type, 
       sum(profit_by_model) as total_profit
from carcompanies
group by model_type;

/* 3. How does the average on-road price differ by model type? */
select model_type, 
       avg(on_road_price_from) as average_on_road_price
from carcompanies
group by model_type;

/* 4. What is the average number of models sold per month by model type? */
select model_type, 
       avg(avg_models_per_month) as avg_models_per_month
from carcompanies
group by model_type;

/* 5. What is the average fuel efficiency for each model type? */
select model_type, 
       avg(mileage) as average_fuel_efficiency
from carcompanies
where fuel_type <> 'electric'
group by model_type;

/* 6. How do sales and profitability correlate for different model types? */
select model_type, 
       sum(no_of_units_sold_in_FY24) as total_sales,
       sum(profit_by_model) as total_profit,
       (sum(profit_by_model) / sum(no_of_units_sold_in_FY24)) as profit_per_unit
from carcompanies
group by model_type;

/* 7. Which model type has the highest estimated revenue in FY24? */
select model_type, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by model_type
order by total_revenue desc
limit 1;

/* 8. What is the average NCAP test score by model type? */
select model_type, 
       avg(ncap_test) as average_ncap_test_score
from carcompanies
group by model_type;

/* 9. How does the seater count vary across model types? */
select model_type, 
       avg(seater_count) as average_seater_count
from carcompanies
group by model_type;

/* 10. What is the average boot space for each model type? */
select model_type, 
       avg(boot_space) as average_boot_space
from carcompanies
group by model_type;


/* G. Impact of NCAP Safety Ratings on Sales and Pricing */
/* 1.  What is the average NCAP rating for each car company in FY24? */
select origin, avg(ncap_test) as average_ncap_rating
from carcompanies
group by origin;

/* 2. What is the relationship between NCAP safety ratings and the average on-road price of cars for each company? */
select origin, avg(on_road_price_from) as avg_on_road_price, avg(ncap_test) as avg_ncap_rating
from carcompanies
group by origin;

/* 3. How many units were sold for each NCAP rating category (1-star, 2-star, etc.)? */
select ncap_test, sum(no_of_units_sold_in_FY24) as units_sold
from carcompanies
group by ncap_test
order by ncap_test desc;

/* 4. What is the average sale price for cars with a 5-star NCAP rating compared to cars with lower ratings? */
select case
           when ncap_test = 5 then '5-star'
           else 'Less than 5-star'
       end as ncap_category,
       avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by ncap_category;

/* 5. Which car brands with a 5-star NCAP rating had the highest number of units sold in FY24? */
select origin, model_name, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
where ncap_test = 5
group by origin, model_name
order by total_units_sold desc;

/* 6. What is the correlation between NCAP rating and profit by model for each brand? */
select origin, ncap_test, sum(profit_by_model) as total_profit
from carcompanies
group by origin, ncap_test
order by origin, ncap_test;

/* 7. Do higher NCAP ratings correlate with a higher seater count in car models? */
select ncap_test, avg(seater_count) as avg_seater_count
from carcompanies
group by ncap_test
order by ncap_test desc;

/* 8. How does NCAP rating influence the estimated revenue for each car company? */
select origin, ncap_test, sum(estimated_revenue) as total_revenue
from carcompanies
group by origin, ncap_test
order by total_revenue desc;

/* 9. What is the distribution of fuel types for cars with 5-star NCAP ratings compared to those with lower ratings? */
select case
           when ncap_test = 5 then '5-star'
           else 'Less than 5-star'
       end as ncap_category,
       fuel_type, count(*) as fuel_type_count
from carcompanies
group by ncap_category, fuel_type;

/* 10. How does the NCAP rating affect the monthly sales of cars across brands? */ 
select origin, ncap_test, avg(avg_models_per_month) as avg_monthly_sales
from carcompanies
group by origin, ncap_test
order by avg_monthly_sales desc;


/* H. Engine Types and Their Impact on Market Performance */
/* 1.  What is the average engine capacity for each car company? */
select origin, avg(engine_capacity) as avg_engine_capacity
from carcompanies
group by origin;

/* 2. How does engine type (e.g., Petrol, Diesel, Electric) correlate with average on-road price across brands? */
select engine_name, origin, avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by engine_name, origin
order by avg_on_road_price desc;

/* 3. Which engine types (Petrol, Diesel, Electric, etc.) have the highest number of units sold in FY24? */
select engine_name, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by engine_name
order by total_units_sold desc;

/* 4. What is the average mileage for each engine type? */
select engine_name, avg(mileage) as avg_mileage
from carcompanies
where fuel_type <> 'electric'
group by engine_name
order by avg_mileage desc;

/* 5. How does engine displacement affect the sales and profitability of cars across different brands? */
select origin, engine_displacement, sum(no_of_units_sold_in_FY24) as total_units_sold, SUM(profit_by_model) as total_profit
from carcompanies
group by origin, engine_displacement
order by total_profit desc;

/* 6. What is the relationship between engine capacity and the pricing of cars? */
select engine_capacity, avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by engine_capacity
order by engine_capacity desc;

/* 7. Which engine types are associated with the highest sales growth in FY24? */
select engine_name, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
where first_sale_date between '2023-01-01' and '2024-12-31'
group by engine_name
order by total_units_sold desc;

/* 8. How does engine type (Petrol, Diesel, Electric, etc.) affect car variant popularity? */
select engine_name, variants, count(*) as variant_count
from carcompanies
group by engine_name, variants
order by variant_count desc;

/* 9. What is the average number of units sold for each engine type across different brands? */
select engine_name, origin, avg(no_of_units_sold_in_FY24) as avg_units_sold
from carcompanies
group by engine_name, origin
order by avg_units_sold desc;

/* 10. Does engine type affect the profitability of car models in different price segments? */
select engine_name, case
                       when on_road_price_from < 1000000 then 'Under 10 Lakh'
                       when on_road_price_from between 1000000 and 2000000 then '10-20 Lakh'
                       else 'Above 20 Lakh'
                   end as price_segment, 
       sum(profit_by_model) as total_profit
from carcompanies
group by engine_name, price_segment
order by total_profit desc;


/* I. Transmission Type and Its Influence on Sales Trends */
/* 1. Sales distribution by Transmission Type (Manual vs Automatic) across all brands */
select transmission_name, 
       count(sale_id) as total_sales, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by transmission_name
order by total_units_sold desc;

/* 2. Average ex-showroom price by Transmission Type */
select transmission_name, 
       avg(ex_showroom_price_from) as avg_ex_showroom_price
from carcompanies
group by transmission_name
order by avg_ex_showroom_price desc;

/* 3. Monthly sales trend based on Transmission Type */
select extract(month from first_sale_date) as sale_month,
       transmission_name, 
       count(sale_id) as total_sales
from carcompanies
group by sale_month, transmission_name
order by sale_month, total_sales desc;

/* 4. Sales performance of Automatic vs Manual Transmission cars by Engine Displacement */
select engine_displacement, 
       transmission_name, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by engine_displacement, transmission_name
order by engine_displacement, total_units_sold desc;

/* 5. Profit comparison for different Transmission Types */
select transmission_name, 
       sum(profit_by_model) as total_profit
from carcompanies
group by transmission_name
order by total_profit desc;

/* 6. Transmission Type’s impact on car variants and sales */
select variants, 
       transmission_name, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by variants, transmission_name
order by total_units_sold desc;

/* 7. Average mileage by Transmission Type */
select transmission_name, 
       avg(mileage) as avg_mileage
from carcompanies
where fuel_type <> 'electric'
group by transmission_name;

/* 8. NCAP safety rating distribution for Manual vs Automatic Transmission cars */
select transmission_name, 
       ncap_test, 
       count(sale_id) as total_sales
from carcompanies
group by transmission_name, ncap_test
order by total_sales desc;

/* 9. Total revenue generated from cars with Automatic vs Manual Transmissions */
select transmission_name, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by transmission_name;

/* 10. Sales of Transmission Types by Car Model Type (SUV vs Sedan) */
select model_type, 
       transmission_name, 
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by model_type, transmission_name
order by total_sales desc;


/* J. Seasonal and Monthly Sales Trends Across Brands */
/* 1. Which months had the highest total sales across all brands in FY24? */
select extract(month from first_sale_date) as month, 
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by extract(month from first_sale_date)
order by total_sales desc;

/* 2. What is the average monthly sales across all brands? */
select avg(no_of_units_sold_in_FY24) as avg_monthly_sales
from carcompanies
where first_sale_date is not null;

/* 3. Which brand had the highest sales in each quarter of FY24? */
select 
    company_name,
    extract(quarter from first_sale_date) as quarter,
    sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by company_name, extract(quarter from first_sale_date)
order by quarter, total_sales desc;

/* 4.  What are the monthly sales trends for SUV models versus Sedans across all brands? */
select extract(month from first_sale_date) as month,
       model_type,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
where model_type in ('SUV', 'Sedan')
group by extract(MONTH FROM first_sale_date), model_type
order by month, model_type;

/* 5. What is the seasonal sales trend for cars with high fuel efficiency (mileage > 20 km/l)? */
select extract(month from first_sale_date) as month,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
where mileage > 20
group by extract(month from first_sale_date)
order by month;

/* 6. How do sales fluctuate based on NCAP safety ratings each month? */
select extract(month from first_sale_date) as month,
       ncap_test,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by extract(month from first_sale_date), ncap_test
order by month, total_sales desc;

/* 7. Which month had the highest sales for each brand? */
select company_name, 
       extract(month from first_sale_date) as month, 
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by company_name, extract(month from first_sale_date)
order by company_name, total_sales desc;

/* 8. What is the correlation between boot space and monthly sales trends? */
select extract(month from first_sale_date) as month,
       avg(boot_space) as avg_boot_space,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by extract(month from first_sale_date)
order by month;

/* 9. What are the seasonal sales trends for cars with manual vs automatic transmissions? */
select extract(month from first_sale_date) as month,
       transmission,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
where transmission in ('Manual', 'Automatic')
group by extract(month from first_sale_date), transmission
order by month;

/* 10. Which months had the most significant sales spikes across all brands, and how does this relate to pricing? */
select extract(month from first_sale_date) as month,
       avg(on_road_price_from) as avg_price,
       sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by extract(month from first_sale_date)
having sum(no_of_units_sold_in_FY24) > 1000 
order by month;


/* K. Price Sensitivity and Market Segmentation */
/* 1. Which car models have the highest and lowest ex-showroom price in each brand? */
select model_name, ex_showroom_price_from, origin
from carcompanies
where ex_showroom_price_from = (select max(ex_showroom_price_from) from carcompanies where origin = carcompanies.origin)
   or ex_showroom_price_from = (select min(ex_showroom_price_from) from carcompanies where origin = carcompanies.origin)
order by origin, ex_showroom_price_from desc;

/* 2. What is the average on-road price across all brands? */
select origin, avg(on_road_price_from) as avg_on_road_price
from carcompanies
group by origin;

/* 3. How does the price vary across different car models in terms of seating capacity? */
select model_name, seater_count, ex_showroom_price_from
from carcompanies
order by seater_count, ex_showroom_price_from desc;

/* 4. What is the relationship between engine capacity and the price of the car? */
select engine_capacity, avg(ex_showroom_price_from) as avg_price
from carcompanies
where fuel_type <> 'electric'
group by engine_capacity
order by engine_capacity;

/* 5. Which fuel type has the highest priced car models? */
select fuel_type, model_name, ex_showroom_price_from
from carcompanies
where ex_showroom_price_from = (select max(ex_showroom_price_from) from carcompanies where fuel_type = carcompanies.fuel_type)
order by fuel_type;

/* 6. How does the price correlate with car variants (e.g., standard, premium, etc.)? */
select variants, avg(ex_showroom_price_from) as avg_price
from carcompanies
group by variants
order by avg_price desc; 

/* 7. Which car models have the highest and lowest on-road price within each engine type? */
select engine_name, model_name, on_road_price_from
from carcompanies
where on_road_price_from = (select max(on_road_price_from) from carcompanies where engine_name = carcompanies.engine_name)
   or on_road_price_from = (select min(on_road_price_from) from carcompanies where engine_name = carcompanies.engine_name)
order by engine_name;

/* 8. What is the distribution of cars by price range across different brands? */
select origin,
       case
           when ex_showroom_price_from < 500000 then 'Under 5 Lakhs'
           when ex_showroom_price_from between 500000 and 1000000 then '5-10 Lakhs'
           when ex_showroom_price_from between 1000000 and 1500000 then '10-15 Lakhs'
           else 'Above 15 Lakhs'
       end as price_range,
       COUNT(*) as car_count
from carcompanies
group by origin, price_range
order by origin, price_range;

/* 9. How does the sales volume compare to the price of cars in each segment (SUV, Sedan, etc.)? */
select model_type, avg(on_road_price_from) as avg_price, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by model_type
order by total_sales desc;

/* 10. What is the price difference between high and low NCAP-rated cars (safety rating)? */
select ncap_test,
       avg(ex_showroom_price_from) as avg_price
from carcompanies
group by ncap_test
order by ncap_test;


/* L. Profitability by Engine Displacement and Capacity */
/* 1. Which engine displacement ranges generate the highest profit by model? */
select engine_displacement, sum(profit_by_model) as total_profit
from carcompanies
group by engine_displacement
order by total_profit desc;

/* 2. What is the average profit for models within different engine capacities? */
select engine_capacity, avg(profit_by_model) as average_profit
from carcompanies
group by engine_capacity
order by average_profit desc;

/* 3. How does the engine displacement impact the profit for each car brand? */
select origin, engine_displacement, sum(profit_by_model) as total_profit
from carcompanies
group by origin, engine_displacement
order by origin, total_profit desc;

/* 4.  Which models with specific engine displacements have the highest profit margin? */
select model_name, engine_displacement, profit_by_model
from carcompanies
where profit_by_model = (select max(profit_by_model) from carcompanies where engine_displacement = carcompanies.engine_displacement)
order by engine_displacement;

/* 5. What is the total profit by engine displacement range across all brands? */
select 
  case
    when engine_displacement < 1.5 then '<1.5L'
    when engine_displacement between 1.5 and 2.0 then '1.5L-2.0L'
    when engine_displacement between 2.0 and 3.0 then '2.0L-3.0L'
    else 'Above 3.0L'
  end as engine_range,
  sum(profit_by_model) as total_profit
from carcompanies
group by engine_range
order by total_profit desc;

/* 6. What engine capacity shows the highest profit per unit sold? */
select engine_capacity, sum(profit_by_model) / sum(no_of_units_sold_in_FY24) as profit_per_unit
from carcompanies
group by engine_capacity
order by profit_per_unit desc;

/* 7. Which car models have the highest engine displacement and their profitability? */
select model_name, engine_displacement, profit_by_model
from carcompanies
where engine_displacement = (select max(engine_displacement) from carcompanies)
order by profit_by_model desc;

/* 8. How does engine capacity affect profitability when considering the number of units sold? */
select engine_capacity, sum(profit_by_model) / sum(no_of_units_sold_in_FY24) as profit_per_unit
from carcompanies
group by engine_capacity
order by profit_per_unit desc;

/* 9. What is the total profitability by engine displacement for each transmission type? */
select transmission_name, engine_displacement, sum(profit_by_model) as total_profit
from carcompanies
group by transmission_name, engine_displacement
order by transmission_name, total_profit desc;

/* 10. Is there a correlation between engine displacement, engine capacity, and profitability? */
select engine_displacement, engine_capacity, sum(profit_by_model) as total_profit
from carcompanies
group by engine_displacement, engine_capacity
order by total_profit desc;

/* M. Seating Capacity vs Sales and Revenue */
/* 1. Total Sales and Revenue by Seating Capacity */
select seater_count, 
       sum(no_of_units_sold_in_FY24) as total_units_sold, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by seater_count
order by total_units_sold desc;

/* 2. Average Price and Sales Based on Seating Capacity */
select seater_count, 
       avg(ex_showroom_price_from) as avg_ex_showroom_price, 
       avg(on_road_price_from) as avg_on_road_price, 
       avg(no_of_units_sold_in_FY24) as avg_units_sold
from carcompanies
group by seater_count
order by seater_count;

/* 3. Sales Performance for Cars with 5-Seater Capacity */
select model_name, 
       no_of_units_sold_in_FY24, 
       estimated_revenue
from carcompanies
where seater_count = 5
order by no_of_units_sold_in_FY24 desc;

/* 4. Revenue Breakdown by Seating Capacity and Model Type */
select model_type, 
       seater_count, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by model_type, seater_count
order by seater_count, total_revenue desc;

/* 5. Profitability of Cars by Seating Capacity */
select seater_count, 
       sum(profit_by_model) as total_profit, 
       sum(loss_by_model) as total_loss
from carcompanies
group by seater_count
order by total_profit desc, total_loss desc;

/* 6. Correlation Between Seating Capacity and NCAP Safety Ratings */
select seater_count, 
       ncap_test, 
       sum(no_of_units_sold_in_FY24) as total_units_sold, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by seater_count, ncap_test
order by seater_count, total_units_sold desc;

/* 7. Top 5 Models with the Highest Revenue Based on Seating Capacity */
select model_name, 
       seater_count, 
       estimated_revenue
from carcompanies
order by estimated_revenue desc
limit 5;

/* 8. Monthly Sales and Revenue Trends by Seating Capacity */
select extract(month from first_sale_date) as month, 
       seater_count, 
       sum(no_of_units_sold_in_FY24) as total_units_sold, 
       sum(estimated_revenue) as total_revenue
from carcompanies
group by month, seater_count
order by month, seater_count;

/* 9. Average Mileage by Seating Capacity */
select seater_count, 
       avg(mileage) as avg_mileage
from carcompanies
where fuel_type <> 'electric'
group by seater_count
order by seater_count;

/* 10.  Seating Capacity vs. Market Segment Analysis */
select seater_count, 
       avg(on_road_price_from) as avg_on_road_price, 
       sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by seater_count
order by total_units_sold desc, avg_on_road_price;


/* N. Boot Space and Consumer Preferences */
/* 1. Which car models have the highest boot space across all brands? */
select model_name, boot_space, company_name
from carcompanies
order by boot_space desc
limit 5;

/* 2. How does boot space correlate with the sales performance of car models? */
select model_name, boot_space, no_of_units_sold_in_FY24
from carcompanies
order by boot_space desc;

/* 3. Which car brands have the largest average boot space? */
select company_name, avg(boot_space) as average_boot_space
from carcompanies
group by company_name
order by average_boot_space desc;

/* 4. Which car models have the smallest boot space? */
select model_name, boot_space
from carcompanies
order by boot_space asc
limit 5;

/* 5. What is the distribution of boot space across different fuel types? */
select fuel_type, avg(boot_space) as average_boot_space
from carcompanies
group by fuel_type
order by average_boot_space desc;

/* 6. What is the boot space distribution by model type (SUV, Sedan, etc.)? */
select model_type, avg(boot_space) as average_boot_space
from carcompanies
group by model_type
order by average_boot_space desc;

/* 7. How does boot space vary with seating capacity? */
select seater_count, avg(boot_space) as average_boot_space
from carcompanies
group by seater_count
order by seater_count;

/* 8. Which cars have more than 500 liters of boot space and their respective sales figures? */
select model_name, boot_space, no_of_units_sold_in_FY24
from carcompanies
where boot_space > 500
order by no_of_units_sold_in_FY24 desc;

/* 9.  What is the average boot space for cars with different NCAP safety ratings? */
select ncap_test, avg(boot_space) as average_boot_space
from carcompanies
group by ncap_test
order by average_boot_space desc;

/* 10. Is there a relationship between the boot space and the engine displacement of cars? */
select engine_displacement, avg(boot_space) as average_boot_space
from carcompanies
group by engine_displacement
order by engine_displacement;


/* O. Manufacturing Locations and Their Impact on Regional Sales */
/* 1. Total Sales by Manufacturing Location */
select manufacturing_locations_in_india, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by manufacturing_locations_in_india;

/* 2. Average Sales per Region */
select manufacturing_locations_in_india, avg(no_of_units_sold_in_FY24) as avg_sales
from carcompanies
group by manufacturing_locations_in_india;

/* 3. Revenue by Manufacturing Location */
select manufacturing_locations_in_india, sum(estimated_revenue) as total_revenue
from carcompanies
group by manufacturing_locations_in_india;

/* 4. Profitability by Manufacturing Location */
select manufacturing_locations_in_india, sum(profit_by_model) as total_profit
from carcompanies
group by manufacturing_locations_in_india;

/* 5. Loss by Manufacturing Location */
select manufacturing_locations_in_india, sum(loss_by_model) as total_loss
from carcompanies
group by manufacturing_locations_in_india;

/* 6. Average Ex-showroom Price by Manufacturing Location */
select manufacturing_locations_in_india, avg(ex_showroom_price_from) as avg_ex_showroom_price
from carcompanies
group by manufacturing_locations_in_india;

/* 7. Correlation between Manufacturing Location and Fuel Type */
select manufacturing_locations_in_india, fuel_type, count(*) as fuel_type_count
from carcompanies
group by manufacturing_locations_in_india, fuel_type;

/* 8. Impact of Manufacturing Location on Seater Count */
select manufacturing_locations_in_india, avg(seater_count) as avg_seater_count
from carcompanies
group by manufacturing_locations_in_india;

/* 9. Transmission Type Popularity by Manufacturing Location */
select manufacturing_locations_in_india, transmission_name, count(*) as transmission_count
from carcompanies
group by manufacturing_locations_in_india, transmission_name
order by manufacturing_locations_in_india, transmission_count desc;

/* 10. Manufacturing Location and NCAP Safety Rating Distribution */
select manufacturing_locations_in_india, ncap_test, count(*) as ncap_count
from carcompanies
group by manufacturing_locations_in_india, ncap_test
order by manufacturing_locations_in_india, ncap_count desc;


/* P. Trends in Car Variant Popularity */
/* 1. Which car variants have the highest number of units sold in FY24? */
select model_name, variants, sum(no_of_units_sold_in_FY24) as total_units_sold
from carcompanies
group by model_name, variants
order by total_units_sold desc
limit 10;

/* 2. What is the average price of car variants across all brands? */
select variants, avg(ex_showroom_price_from) as avg_price
from carcompanies
group by variants
order by avg_price desc;

/* 3. Which variants have the highest profit across all car companies? */
select variants, sum(profit_by_model) as total_profit
from carcompanies
group by variants
order by total_profit desc
limit 10;

/* 4. What is the average mileage for each car variant? */
select variants, avg(mileage) as avg_mileage
from carcompanies
group by variants
order by avg_mileage desc;

/* 5. Which car variants have the highest number of seater count? */
select variants, max(seater_count) as max_seater_count
from carcompanies
group by variants
order by max_seater_count desc;

/* 6. How do car variants with higher engine displacement perform in terms of sales? */
select variants, engine_displacement, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by variants, engine_displacement
order by total_sales desc;

/* 7. What is the relationship between car variants' tank capacity and their sales in FY24? */
select variants, tank_capacity, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by variants, tank_capacity
order by total_sales desc;

/* 8. Which car variants have the highest average units sold per month? */
select variants, avg(avg_models_per_month) as avg_units_per_month
from carcompanies
group by variants
order by avg_units_per_month desc;

/* 9. How do different fuel types affect the popularity of car variants? */
select variants, fuel_type, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by variants, fuel_type
order by total_sales desc;

/* 10. Which car variants have the highest NCAP safety ratings, and how do they perform in sales? */
select variants, ncap_test, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
group by variants, ncap_test
order by total_sales desc;


/* Q. Electric Vehicle (EV) Performance and Adoption Trends */
/* 1. Which car brands have the highest number of EV models in FY24? */
select origin, count(distinct model_name) as ev_model_count
from carcompanies
where fuel_type = 'Electric'
group by origin
order by ev_model_count desc;

/* 2. What is the average sale price of EVs across brands? */
select avg(on_road_price_from) as avg_ev_price
from carcompanies
where fuel_type = 'Electric';

/* 3. Which electric vehicle models have the highest sales in FY24? */
select model_name, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
where fuel_type = 'Electric'
group by model_name
order by total_sales desc
limit 10;

/* 4. What is the total revenue generated from EV models in FY24? */
select sum(estimated_revenue) as total_ev_revenue
from carcompanies
where fuel_type = 'Electric';

/* 5. Which brands have the best NCAP safety ratings for their EV models? */
select origin, avg(ncap_test) as avg_ncap_rating
from carcompanies
where fuel_type = 'Electric' and ncap_test is not null
group by origin
order by avg_ncap_rating desc;

/* 6. What is the average range of electric vehicles? */
select avg(mileage) as avg_ev_range
from carcompanies
where fuel_type = 'Electric';

/* 7. How many EV models have a higher than average engine capacity? */
select count(distinct model_name) as ev_count_above_avg_capacity
from carcompanies
where fuel_type = 'Electric' and engine_capacity > 
    (select avg(engine_capacity) from carcompanies where fuel_type = 'Electric');
    
/* 8. What is the market share of EVs in the total sales of all brands? */
select 
    (sum(no_of_units_sold_in_FY24) / 
    (select sum(no_of_units_sold_in_FY24) from carcompanies)) * 100 as ev_market_share
from carcompanies
where fuel_type = 'Electric';

/* 9. How have EV sales grown month-over-month in FY24? */
select extract(month from first_sale_date) as month, 
       sum(no_of_units_sold_in_FY24) as monthly_ev_sales
from carcompanies
where fuel_type = 'Electric'
group by month
order by month;

/* 10. Which electric vehicle variants are most popular in terms of sales? */
select variants, sum(no_of_units_sold_in_FY24) as total_sales
from carcompanies
where fuel_type = 'Electric'
group by variants
order by total_sales desc
limit 10;